// ----------------- Monaco Editor Setup -----------------
require.config({ paths: { 'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.45.0/min/vs' }});
require(["vs/editor/editor.main"], function () {
  window.editor = monaco.editor.create(document.getElementById("editor"), {
    value: "// Select a file from the sidebar to load its contents...",
    language: "javascript",
    theme: "vs-dark",
    fontSize: 14,
  });
});

// ----------------- Dummy File Contents -----------------
let files = {
  "main.py": "print('Hello from main.py!')",
  "index.html": "<!DOCTYPE html>\n<html>\n<head><title>Demo</title></head>\n<body>\n<h1>Hello World</h1>\n</body>\n</html>",
  "style.css": "body { background: #eee; font-family: Arial; }",
  "script.js": "console.log('Hello from script.js!');",
  "README.md": "# Trae SOLO IDE\nThis is a demo file explorer + editor."
};

let selectedFileLi = null;

// ----------------- Open File in Editor -----------------
function openFile(filename, liElement) {
  const content = files[filename] || "";
  const ext = filename.split(".").pop();
  editor.setValue(content);
  monaco.editor.setModelLanguage(editor.getModel(), ext === "py" ? "python" : ext);

  if (selectedFileLi) selectedFileLi.classList.remove("selected");
  liElement.classList.add("selected");
  selectedFileLi = liElement;
}

// ----------------- Mock AI Function (Alert Version) -----------------
function askAI() {
  const msg = prompt("Enter your question for AI:");
  if (!msg) return;
  sendToBackend(msg);
}

// ----------------- Auto-complete (Live Typing) -----------------
function autoComplete() {
  const suggestion = [
    "// AI suggests more code here...",
    "function greet(name) {",
    "    console.log('Hello, ' + name + '!');",
    "}",
    "greet('World');"
  ];

  let i = 0;
  const typingInterval = setInterval(() => {
    const currentValue = editor.getValue();
    editor.setValue(currentValue + (currentValue ? "\n" : "") + suggestion[i]);
    i++;
    if (i >= suggestion.length) clearInterval(typingInterval);
  }, 400);
}

// ----------------- Project Generator -----------------
function generateProject() {
  const newProject = {
    "app": {
      "main.py": "print('Hello from app/main.py')",
      "utils.py": "def helper():\n    return 'Helper function'"
    },
    "web": {
      "index.html": "<!DOCTYPE html>\n<html>\n<body>\n<h1>Welcome to Trae SOLO</h1>\n</body>\n</html>",
      "style.css": "body { font-family: Arial; background: #fafafa; }"
    },
    "README.md": "# Generated Project\nThis is a mock project generated by Trae SOLO IDE."
  };

  const fileList = document.getElementById("file-list");
  fileList.innerHTML = "";
  selectedFileLi = null;

  function renderTree(tree, parentUl = fileList) {
    for (let key in tree) {
      const li = document.createElement("li");

      if (typeof tree[key] === "string") {
        li.textContent = key;
        li.onclick = (e) => { e.stopPropagation(); openFile(key, li); };
      } else {
        li.textContent = "📁 " + key;
        li.style.cursor = "pointer";

        const ul = document.createElement("ul");
        ul.style.listStyle = "none";
        ul.style.paddingLeft = "15px";
        ul.style.display = "none";
        li.appendChild(ul);

        li.onclick = (e) => {
          e.stopPropagation();
          if (ul.style.display === "none") {
            ul.style.display = "block";
            li.textContent = "📂 " + key;
          } else {
            ul.style.display = "none";
            li.textContent = "📁 " + key;
          }
        };

        renderTree(tree[key], ul);
      }

      parentUl.appendChild(li);
    }
  }

  renderTree(newProject);
  files = flattenFiles(newProject);
  alert("📂 Mock Project Generated! Click files to view in editor.");
}

function flattenFiles(tree) {
  let result = {};
  for (let key in tree) {
    if (typeof tree[key] === "string") {
      result[key] = tree[key];
    } else {
      Object.assign(result, flattenFiles(tree[key]));
    }
  }
  return result;
}

// ----------------- Chat Functionality -----------------
async function sendMessage(event) {
  if (event.key === "Enter") {
    const input = document.getElementById("chat-input");
    const msg = input.value.trim();
    if (!msg) return;

    const chatBox = document.getElementById("chat-box");

    // User bubble
    const userDiv = document.createElement("div");
    userDiv.className = "chat-message user";
    userDiv.textContent = msg;
    chatBox.appendChild(userDiv);

    sendToBackend(msg);
    input.value = "";
    chatBox.scrollTop = chatBox.scrollHeight;
  }
}

async function sendToBackend(msg) {
  const chatBox = document.getElementById("chat-box");
  try {
    const response = await fetch("http://127.0.0.1:5000/ask", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ message: msg }),
    });
    const data = await response.json();

    const aiDiv = document.createElement("div");
    aiDiv.className = "chat-message ai";
    aiDiv.textContent = data.reply;
    chatBox.appendChild(aiDiv);
    chatBox.scrollTop = chatBox.scrollHeight;
  } catch (err) {
    const aiDiv = document.createElement("div");
    aiDiv.className = "chat-message ai";
    aiDiv.textContent = "🤖 Backend not reachable!";
    chatBox.appendChild(aiDiv);
  }
}
